//
// Generated file, do not edit! Created by nedtool 4.6 from src/node/application/IDSTest/AgentPacket.msg.
//

#ifndef _AGENTPACKET_M_H_
#define _AGENTPACKET_M_H_

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0406
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



// cplusplus {{
#include "ApplicationPacket_m.h"
// }}

/**
 * Class generated from <tt>src/node/application/IDSTest/AgentPacket.msg:7</tt> by nedtool.
 * <pre>
 * packet AgentPacket extends ApplicationPacket
 * {
 *     char content[];
 * }
 * </pre>
 */
class AgentPacket : public ::ApplicationPacket
{
  protected:
    char *content_var; // array ptr
    unsigned int content_arraysize;

  private:
    void copy(const AgentPacket& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const AgentPacket&);

  public:
    AgentPacket(const char *name=NULL, int kind=0);
    AgentPacket(const AgentPacket& other);
    virtual ~AgentPacket();
    AgentPacket& operator=(const AgentPacket& other);
    virtual AgentPacket *dup() const {return new AgentPacket(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual void setContentArraySize(unsigned int size);
    virtual unsigned int getContentArraySize() const;
    virtual char getContent(unsigned int k) const;
    virtual void setContent(unsigned int k, char content);
};

inline void doPacking(cCommBuffer *b, AgentPacket& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, AgentPacket& obj) {obj.parsimUnpack(b);}


#endif // ifndef _AGENTPACKET_M_H_

